# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

ENV["FIREBASE_TOKEN"] = "1//0gKAKIORrd2OsCgYIARAAGBASNwF-L9IrhPMFFXJZvcPEtTODz3fnj66nCGIv_QCRkQNmIzW0r_phtoE9FesCSQodguO6-Tn0pzs"

update_fastlane

default_platform(:ios)

platform :ios do
  desc "Distributes the HMSVideoExample app on Firebase"
  lane :beta do

    increment_build_number 
    
    increment_version_number(
      bump_type: "minor" 
    )

    build_app(scheme: "HMSVideo_Example",
              workspace: "HMSVideoExample.xcworkspace")
    
    firebase_app_distribution(
      app: "1:1018747429814:ios:97b0916de004d8ad76d717"
    )
  end
end
