# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

ENV["FIREBASE_TOKEN"] = "1//0gXmd2UmtDh6PCgYIARAAGBASNwF-L9IrahfukyD1EiteVSYNH-zhSSjWFbPly6hA1nGh4pxPMKR0ptadvl5ZesFWEOGn63obux8"

update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Archives & generates iPA for Example App"
  lane :build_example_app do

    setup_ci

    match(
      type: "development",
      readonly: true,
      shallow_clone: true,
      readonly: true,
      git_basic_authorization: Base64.strict_encode64("100mstech:038befa3f9e1c8cdf651fdd50faa4f7f91087df2"),
    )

    gym(
      scheme: "HMSVideo_Example",
      export_options: {
        method: "development",
        provisioningProfiles: { 
          "live.100ms.videoapp" => "match Development live.100ms.videoapp"
        }
      }
    )
  end

  # desc "Runs Unit Tests"
  # lane :tests do
  #   scan(scheme: "HMSVideo_Tests",
  #       devices: ["iPhone 12", "iPhone 12 Pro"],
  #       buildlog_path: "./fastlane/fastlane-buildlog",
  #       derived_data_path: "~/Library/Developer/Xcode/DerivedData")
  # end

  desc "Distributes the HMSVideoExample app on Firebase"
  lane :upload_on_firebase do

    increment_build_number 
    
    increment_version_number(
      bump_type: "patch" 
    )
    
    build_example_app 
    
    firebase_app_distribution(
      app: "1:1018747429814:ios:1ea1d6ba732bf85976d717",
      release_notes: changelog_from_git_commits
    )
  end
end
