name: Swift

on:
  push:
    branches:  
        - main
  pull_request:

jobs:    
  test:
    name: Build
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.5.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Build Example app
      run: |
              ls -al ~/.ssh
              cd Example
              bundle install
              bundle exec fastlane match development git_basic_authorization:ENV[\"AUTH\"] --readonly
              pod install
              bundle exec fastlane build_example_app
              
# name: "build-test"
# on: # rebuild any PRs and main branch changes
#   pull_request:
#   push:
#     branches:
#       - master

# jobs:
#   build: # make sure build/ci work properly
#     runs-on: macOS-latest
#     timeout-minutes: 30
#     steps:
#     - uses: actions/checkout@v2
#     - run: ./Build

# name: Super-Linter

# # Run this workflow every time a new commit pushed to your repository
# on: push

# jobs:
#   # Set the job key. The key is displayed as the job name
#   # when a job name is not provided
#   super-lint:
#     # Name the Job
#     name: Lint code base
#     # Set the type of machine to run on
#     runs-on: ubuntu-latest

#     steps:
#       # Checks out a copy of your repository on the ubuntu-latest machine
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # Runs the Super-Linter action
#       - name: Run Super-Linter
#         uses: github/super-linter@v3
#         env:
#           DEFAULT_BRANCH: main
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
